# Generated by Django 5.1.6 on 2025-03-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('sl', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('all_project', models.CharField(max_length=200)),
                ('followup', models.DateTimeField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=50)),
                ('associate', models.CharField(max_length=100)),
                ('team_leader', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('last_discussion', models.TextField(blank=True, null=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('lead_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
